# This is a template Makefile generated by rpcgen

# Parameters

CLIENT = oauth_client
SERVER = oauth_server
SERVER_OUT = server.out
CLIENT_OUT = client.out

SOURCES_CLNT.cpp =
SOURCES_CLNT.h =
SOURCES_SVC.cpp =
SOURCES_SVC.h =
SOURCES.x = oauth.x

TARGETS_SVC.cpp = oauth_svc.cpp oauth_server.cpp oauth_xdr.cpp
TARGETS_CLNT.cpp = oauth_clnt.cpp oauth_client.cpp oauth_xdr.cpp
TARGETS = oauth.h oauth_xdr.cpp oauth_clnt.cpp oauth_svc.cpp oauth_client.cpp oauth_server.cpp

OBJECTS_CLNT = $(SOURCES_CLNT.cpp:%.cpp=%.o) $(TARGETS_CLNT.cpp:%.cpp=%.o)
OBJECTS_SVC = $(SOURCES_SVC.cpp:%.cpp=%.o) $(TARGETS_SVC.cpp:%.cpp=%.o)

# Compiler flags 

CXXFLAGS += -g -I/usr/include/tirpc
LDLIBS += -lnsl -ltirpc
RPCGENFLAGS = -C

# Targets 

all : $(CLIENT) $(SERVER)

$(TARGETS) : $(SOURCES.x) 
	rpcgen $(RPCGENFLAGS) $(SOURCES.x)

$(OBJECTS_CLNT): $(SOURCES_CLNT.cpp) $(SOURCES_CLNT.h) $(TARGETS_CLNT.cpp)

$(OBJECTS_SVC): $(SOURCES_SVC.cpp) $(SOURCES_SVC.h) $(TARGETS_SVC.cpp)

$(CLIENT) : $(OBJECTS_CLNT) 
	$(CXX) -o $(CLIENT) $(OBJECTS_CLNT) $(LDLIBS) 

$(SERVER) : $(OBJECTS_SVC) 
	$(CXX) -o $(SERVER) $(OBJECTS_SVC) $(LDLIBS)

clean:
	rm -f $(OBJECTS_CLNT) $(OBJECTS_SVC) $(CLIENT) $(SERVER) $(SERVER_OUT) $(CLIENT_OUT) 
