/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OAUTH_H_RPCGEN
#define _OAUTH_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct AuthRequest {
	char *user_id;
};
typedef struct AuthRequest AuthRequest;

struct AuthResponse {
	char *request_token;
};
typedef struct AuthResponse AuthResponse;

struct AccessTokenRequest {
	char *user_id;
	char *request_token;
	bool_t refresh;
};
typedef struct AccessTokenRequest AccessTokenRequest;

struct RefreshTokenRequest {
	char *access_token;
	char *refresh_token;
};
typedef struct RefreshTokenRequest RefreshTokenRequest;

struct AccessTokenResponse {
	char *access_token;
	char *refresh_token;
	int ttl;
};
typedef struct AccessTokenResponse AccessTokenResponse;

struct ValidateActionRequest {
	char *operation;
	char *resource;
	char *access_token;
};
typedef struct ValidateActionRequest ValidateActionRequest;

struct ValidateActionResponse {
	char *response;
};
typedef struct ValidateActionResponse ValidateActionResponse;

struct ApproveRequestToken {
	char *user_id;
	char *request_token;
};
typedef struct ApproveRequestToken ApproveRequestToken;

#define OAUTH_PROG 0x20000001
#define OAUTH_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define RequestAuthorization 1
extern  AuthResponse * requestauthorization_1(AuthRequest , CLIENT *);
extern  AuthResponse * requestauthorization_1_svc(AuthRequest , struct svc_req *);
#define RequestAccessToken 2
extern  AccessTokenResponse * requestaccesstoken_1(AccessTokenRequest , CLIENT *);
extern  AccessTokenResponse * requestaccesstoken_1_svc(AccessTokenRequest , struct svc_req *);
#define RefreshAccessToken 3
extern  AccessTokenResponse * refreshaccesstoken_1(RefreshTokenRequest , CLIENT *);
extern  AccessTokenResponse * refreshaccesstoken_1_svc(RefreshTokenRequest , struct svc_req *);
#define ValidateAction 4
extern  ValidateActionResponse * validateaction_1(ValidateActionRequest , CLIENT *);
extern  ValidateActionResponse * validateaction_1_svc(ValidateActionRequest , struct svc_req *);
#define ApproveRequest 5
extern  void * approverequest_1(ApproveRequestToken , CLIENT *);
extern  void * approverequest_1_svc(ApproveRequestToken , struct svc_req *);
extern int oauth_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RequestAuthorization 1
extern  AuthResponse * requestauthorization_1();
extern  AuthResponse * requestauthorization_1_svc();
#define RequestAccessToken 2
extern  AccessTokenResponse * requestaccesstoken_1();
extern  AccessTokenResponse * requestaccesstoken_1_svc();
#define RefreshAccessToken 3
extern  AccessTokenResponse * refreshaccesstoken_1();
extern  AccessTokenResponse * refreshaccesstoken_1_svc();
#define ValidateAction 4
extern  ValidateActionResponse * validateaction_1();
extern  ValidateActionResponse * validateaction_1_svc();
#define ApproveRequest 5
extern  void * approverequest_1();
extern  void * approverequest_1_svc();
extern int oauth_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_AuthRequest (XDR *, AuthRequest*);
extern  bool_t xdr_AuthResponse (XDR *, AuthResponse*);
extern  bool_t xdr_AccessTokenRequest (XDR *, AccessTokenRequest*);
extern  bool_t xdr_RefreshTokenRequest (XDR *, RefreshTokenRequest*);
extern  bool_t xdr_AccessTokenResponse (XDR *, AccessTokenResponse*);
extern  bool_t xdr_ValidateActionRequest (XDR *, ValidateActionRequest*);
extern  bool_t xdr_ValidateActionResponse (XDR *, ValidateActionResponse*);
extern  bool_t xdr_ApproveRequestToken (XDR *, ApproveRequestToken*);

#else /* K&R C */
extern bool_t xdr_AuthRequest ();
extern bool_t xdr_AuthResponse ();
extern bool_t xdr_AccessTokenRequest ();
extern bool_t xdr_RefreshTokenRequest ();
extern bool_t xdr_AccessTokenResponse ();
extern bool_t xdr_ValidateActionRequest ();
extern bool_t xdr_ValidateActionResponse ();
extern bool_t xdr_ApproveRequestToken ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OAUTH_H_RPCGEN */
